version: "3.8"

services:
  backend:
    build: .
    container_name: pluton-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env
    restart: unless-stopped
